### ISSUE TITLE
Not an issue

### ISSUE THREAD

**Issue by picoroma** [target/plugin-for-rundeck-to-execute-sap-modules#2]
Sorry for write you here.
It's possible to use this plugin or future developments, for perform some  MASS action on SAP systems.
For example:
Mass Loch\Unlock user (scheduled by rundeck)
Transport of CR at scheduled time or simply mass transport of CR from a list of them
THX

**Comment by venkategowdap** [comment]
@picoroma : This plugin has developed to address specific use cases to trigger SAP BW and R3 jobs using SAPJCO library functionalities . Thanks
